on:
  pull_request:
    branches:
      - main
name: Pull request workflow
jobs:
  validate_earn_strategies:
    name: Validate App Store
    runs-on: ubuntu-latest
    steps:
    
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          submodules: true
          
      - name: Install JSON-Schema-Validator
        run: npm install -g jsonschema

      - name: Validate App Store Schema
        run: jsonschema -i ./cms/apps/applications.json ./schemas/applications.schema.json
