on:
  pull_request:
    branches:
      - main
name: Pull request workflow
jobs:
  validate_earn_strategies:
    name: Validate Landing Page Content
    runs-on: ubuntu-latest
    steps:
    
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          submodules: true
          
      - name: Install JSON-Schema-Validator
        run: npm install -g jsonschema

      - name: Validate Landing Page Schema
        run: jsonschema -i ./cms/landing-page/landing-page.json ./schemas/landing-page.schema.json
