on:
  pull_request:
    branches:
      - main
name: Pull request workflow
jobs:
  validate_earn_strategies:
    name: Validate Earn Strategies
    runs-on: ubuntu-latest
    steps:
    
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          submodules: true
          
      - name: Install JSON-Schema-Validator
        run: npm install -g jsonschema

      - name: Validate Earn Strategies Schema
        run: |
          for file in $(find . -name 'strategies.json'); do
            if ! jsonschema -i "$file" ./strategies.schema.json; then
              exit 1
            fi
          done
